### ISSUE TITLE
Conda channel

### ISSUE THREAD

**Issue by jordan-melendez** [poliastro/pycephes#5]
When I used

```
conda install pycephes --channel poliastro
```

I got the following message:

Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/poliastro/noarch/repodata.json>
Elapsed: 00:00.328616
CF-RAY: 462328916ac892b8-SJC

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/poliastro

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by Juanlu001** [comment]
Hi @jordan-melendez, thanks for your interest! I think I removed the poliastro conda channel to direct people to conda-forge but this package was never ported. Also, I think @horta did some work related to this but I'm not sure what's the status. @horta should we create feedstocks for both cephes and pycephes? What do you think?

**Comment by horta** [comment]
Hi @Juanlu001 , I think one package would be enough, no? I will have a look at its status and report back!

**Comment by jordan-melendez** [comment]
I did install the ncephes-py package and it works well but unfortunately doesn't have `hyp2f1`, which is what I need. I forked that repo and may submit a PR soon if that's the best course of action. Thanks!

**Comment by horta** [comment]
That is great! Yesterday I worked on the C hcephes library: https://github.com/limix/hcephes/tree/develop which I depend on for the ncephes for python. I will be working on making available more functions in Python as well.

**Comment by Juanlu001** [comment]
> Hi @Juanlu001 , I think one package would be enough, no? I will have a look at its status and report back!

I totally agree :) As soon as you have all the functions in hcephes and ncephes that I had in cephes and pycephes, I will mark both repositories as ["No maintenance intended"](http://unmaintained.tech/).

**Comment by horta** [comment]
Thanks =) I'm working on that. The release should be ready in a couple of minutes/hours.

**Comment by horta** [comment]
Released for pypi: https://github.com/limix/ncephes
It will be on conda-forge today =)

**Comment by astrojuanlu** [comment]
@jordan-melendez I just tried ncephes and works perfectly, please check it out :)

@horta, I abandon this project in favor of yours. Thanks for picking up this effort!

**Comment by horta** [comment]
Thanks a lot =)

**Comment by jordan-melendez** [comment]
@horta thank you!! Just tried the conda version, and it works. Though, don't forget to change the readme, since `cprob` can no longer be imported.
